apiVersion: v1
kind: Service
metadata:
  name: mike-zebra-age
  namespace: prj-mike-test
spec:
  selector:
    app: mike-zebra-age
  ports:
    - name: "grpc"
      port: 80
      targetPort: 5380
    - name: "prometheus"
      port: 5381
      targetPort: 5381