apiVersion: apps/v1
kind: Deployment
metadata:
  name: mike-zebra-flake
  namespace: prj-mike-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mike-zebra-flake
  template:
    metadata:
      labels:
        app: mike-zebra-flake
    spec:
      containers:
      - name: mike-zebra-flake
        image: hub.ucloudadmin.com/mike/flake:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 5180
          - containerPort: 5181
        readinessProbe:
          exec:
            command: ["/usr/local/bin/grpc_health_probe", "-addr=:5180"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/usr/local/bin/grpc_health_probe", "-addr=:5180"]
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"