apiVersion: v1
kind: Service
metadata:
  name: mike-zebra-flake
  namespace: prj-mike-test
spec:
  selector:
    app: mike-zebra-flake
  ports:
    - name: "grpc"
      port: 80
      targetPort: 5180
    - name: "prometheus"
      port: 5181
      targetPort: 5181