apiVersion: v1
kind: Service
metadata:
  name: mike-zebra-bank
  namespace: prj-mike-test
spec:
  selector:
    app: mike-zebra-bank
  ports:
    - name: "grpc"
      port: 80
      targetPort: 5580
    - name: "prometheus"
      port: 5581
      targetPort: 5581