apiVersion: v1
kind: Service
metadata:
  name: mike-zebra-email
  namespace: prj-mike-test
spec:
  selector:
    app: mike-zebra-email
  ports:
    - name: "grpc"
      port: 80
      targetPort: 5480
    - name: "prometheus"
      port: 5481
      targetPort: 5481