apiVersion: v1
kind: Service
metadata:
  name: mike-zebra-cellphone
  namespace: prj-mike-test
spec:
  selector:
    app: mike-zebra-cellphone
  ports:
    - name: "grpc"
      port: 80
      targetPort: 5680
    - name: "prometheus"
      port: 5681
      targetPort: 5681